/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import edu.kit.cbc.web.model.Condition;
import edu.kit.cbc.web.model.Position;
import edu.kit.cbc.web.model.Statement;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Compostion Statement
 */
@Schema(name = "composition", description = "Compostion Statement")
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class Composition implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_STATEMENT_TYPE = "statementType";
    private String statementType;

    public static final String JSON_PROPERTY_ID = "id";
    private Long id;

    public static final String JSON_PROPERTY_PROVEN = "proven";
    private Boolean proven;

    public static final String JSON_PROPERTY_COMMENT = "comment";
    private String comment;

    public static final String JSON_PROPERTY_PRE_CONDITION = "preCondition";
    private Condition preCondition;

    public static final String JSON_PROPERTY_POST_CONDITION = "postCondition";
    private Condition postCondition;

    public static final String JSON_PROPERTY_POSITION = "position";
    private Position position;

    public static final String JSON_PROPERTY_INTERMEDIATE_CONDITION = "intermediateCondition";
    private Condition intermediateCondition;

    public static final String JSON_PROPERTY_LEFT_STATEMENT = "leftStatement";
    private Statement leftStatement;

    public static final String JSON_PROPERTY_RIGHT_STATEMENT = "rightStatement";
    private Statement rightStatement;

    public Composition(String name, String statementType, Long id, Boolean proven, String comment, Condition preCondition, Condition postCondition, Position position, Condition intermediateCondition, Statement leftStatement, Statement rightStatement) {
        this.name = name;
        this.statementType = statementType;
        this.id = id;
        this.proven = proven;
        this.comment = comment;
        this.preCondition = preCondition;
        this.postCondition = postCondition;
        this.position = position;
        this.intermediateCondition = intermediateCondition;
        this.leftStatement = leftStatement;
        this.rightStatement = rightStatement;
    }

    public Composition name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @NotNull
    @Schema(name = "name", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Composition statementType(String statementType) {
        this.statementType = statementType;
        return this;
    }

    /**
     * Get statementType
     * @return statementType
     */
    @NotNull
    @Schema(name = "statementType", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getStatementType() {
        return statementType;
    }

    public void setStatementType(String statementType) {
        this.statementType = statementType;
    }

    public Composition id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Composition proven(Boolean proven) {
        this.proven = proven;
        return this;
    }

    /**
     * Get proven
     * @return proven
     */
    @NotNull
    @Schema(name = "proven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getProven() {
        return proven;
    }

    public void setProven(Boolean proven) {
        this.proven = proven;
    }

    public Composition comment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     * @return comment
     */
    @NotNull
    @Schema(name = "comment", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Composition preCondition(Condition preCondition) {
        this.preCondition = preCondition;
        return this;
    }

    /**
     * Get preCondition
     * @return preCondition
     */
    @Valid
    @NotNull
    @Schema(name = "preCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPreCondition() {
        return preCondition;
    }

    public void setPreCondition(Condition preCondition) {
        this.preCondition = preCondition;
    }

    public Composition postCondition(Condition postCondition) {
        this.postCondition = postCondition;
        return this;
    }

    /**
     * Get postCondition
     * @return postCondition
     */
    @Valid
    @NotNull
    @Schema(name = "postCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPostCondition() {
        return postCondition;
    }

    public void setPostCondition(Condition postCondition) {
        this.postCondition = postCondition;
    }

    public Composition position(Position position) {
        this.position = position;
        return this;
    }

    /**
     * Get position
     * @return position
     */
    @Valid
    @NotNull
    @Schema(name = "position", requiredMode = Schema.RequiredMode.REQUIRED)
    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    public Composition intermediateCondition(Condition intermediateCondition) {
        this.intermediateCondition = intermediateCondition;
        return this;
    }

    /**
     * Get intermediateCondition
     * @return intermediateCondition
     */
    @Valid
    @NotNull
    @Schema(name = "intermediateCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getIntermediateCondition() {
        return intermediateCondition;
    }

    public void setIntermediateCondition(Condition intermediateCondition) {
        this.intermediateCondition = intermediateCondition;
    }

    public Composition leftStatement(Statement leftStatement) {
        this.leftStatement = leftStatement;
        return this;
    }

    /**
     * Get leftStatement
     * @return leftStatement
     */
    @Valid
    @NotNull
    @Schema(name = "leftStatement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getLeftStatement() {
        return leftStatement;
    }

    public void setLeftStatement(Statement leftStatement) {
        this.leftStatement = leftStatement;
    }

    public Composition rightStatement(Statement rightStatement) {
        this.rightStatement = rightStatement;
        return this;
    }

    /**
     * Get rightStatement
     * @return rightStatement
     */
    @Valid
    @NotNull
    @Schema(name = "rightStatement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getRightStatement() {
        return rightStatement;
    }

    public void setRightStatement(Statement rightStatement) {
        this.rightStatement = rightStatement;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Composition composition = (Composition) o;
        return Objects.equals(this.name, composition.name) &&
            Objects.equals(this.statementType, composition.statementType) &&
            Objects.equals(this.id, composition.id) &&
            Objects.equals(this.proven, composition.proven) &&
            Objects.equals(this.comment, composition.comment) &&
            Objects.equals(this.preCondition, composition.preCondition) &&
            Objects.equals(this.postCondition, composition.postCondition) &&
            Objects.equals(this.position, composition.position) &&
            Objects.equals(this.intermediateCondition, composition.intermediateCondition) &&
            Objects.equals(this.leftStatement, composition.leftStatement) &&
            Objects.equals(this.rightStatement, composition.rightStatement);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, statementType, id, proven, comment, preCondition, postCondition, position, intermediateCondition, leftStatement, rightStatement);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Composition {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    statementType: ").append(toIndentedString(statementType)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    proven: ").append(toIndentedString(proven)).append("\n");
        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    preCondition: ").append(toIndentedString(preCondition)).append("\n");
        sb.append("    postCondition: ").append(toIndentedString(postCondition)).append("\n");
        sb.append("    position: ").append(toIndentedString(position)).append("\n");
        sb.append("    intermediateCondition: ").append(toIndentedString(intermediateCondition)).append("\n");
        sb.append("    leftStatement: ").append(toIndentedString(leftStatement)).append("\n");
        sb.append("    rightStatement: ").append(toIndentedString(rightStatement)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

