/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import edu.kit.cbc.web.model.Condition;
import edu.kit.cbc.web.model.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Diagramm file
 */
@Schema(name = "diagramm", description = "Diagramm file")
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class Diagramm implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_URN = "urn";
    private String urn;

    public static final String JSON_PROPERTY_INODE_TYPE = "inodeType";
    private String inodeType;

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        CBC_FORMULA("CBCFormula");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_TYPE = "type";
    private TypeEnum type;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_PROVEN = "proven";
    private Boolean proven;

    public static final String JSON_PROPERTY_COMMENT = "comment";
    private String comment;

    /**
     * Gets or Sets compostionTechnique
     */
    public enum CompostionTechniqueEnum {
        CONTRACT_OVERRIDING("CONTRACT_OVERRIDING");

        private String value;

        CompostionTechniqueEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static CompostionTechniqueEnum fromValue(String value) {
            for (CompostionTechniqueEnum b : CompostionTechniqueEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_COMPOSTION_TECHNIQUE = "compostionTechnique";
    private CompostionTechniqueEnum compostionTechnique;

    public static final String JSON_PROPERTY_CLASS_NAME = "className";
    private String className;

    public static final String JSON_PROPERTY_METHODE_NAME = "methodeName";
    private String methodeName;

    public static final String JSON_PROPERTY_JAVA_VARIABLES = "javaVariables";
    private List<String> javaVariables = new ArrayList<>();

    public static final String JSON_PROPERTY_GLOBAL_CONDITIONS = "globalConditions";
    private List<@Valid Condition> globalConditions = new ArrayList<>();

    public static final String JSON_PROPERTY_PRE_CONDITION = "preCondition";
    private String preCondition;

    public static final String JSON_PROPERTY_POST_CONDITION = "postCondition";
    private String postCondition;

    public static final String JSON_PROPERTY_STATEMENT = "statement";
    private Statement statement;

    public Diagramm(String urn, String inodeType, TypeEnum type, String name, Boolean proven, String comment, CompostionTechniqueEnum compostionTechnique, String className, String methodeName, List<String> javaVariables, List<@Valid Condition> globalConditions, String preCondition, String postCondition, Statement statement) {
        this.urn = urn;
        this.inodeType = inodeType;
        this.type = type;
        this.name = name;
        this.proven = proven;
        this.comment = comment;
        this.compostionTechnique = compostionTechnique;
        this.className = className;
        this.methodeName = methodeName;
        this.javaVariables = javaVariables;
        this.globalConditions = globalConditions;
        this.preCondition = preCondition;
        this.postCondition = postCondition;
        this.statement = statement;
    }

    public Diagramm urn(String urn) {
        this.urn = urn;
        return this;
    }

    /**
     * Get urn
     * @return urn
     */
    @NotNull
    @Schema(name = "urn", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getUrn() {
        return urn;
    }

    public void setUrn(String urn) {
        this.urn = urn;
    }

    public Diagramm inodeType(String inodeType) {
        this.inodeType = inodeType;
        return this;
    }

    /**
     * Get inodeType
     * @return inodeType
     */
    @NotNull
    @Schema(name = "inodeType", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getInodeType() {
        return inodeType;
    }

    public void setInodeType(String inodeType) {
        this.inodeType = inodeType;
    }

    public Diagramm type(TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     */
    @NotNull
    @Schema(name = "type", requiredMode = Schema.RequiredMode.REQUIRED)
    public TypeEnum getType() {
        return type;
    }

    public void setType(TypeEnum type) {
        this.type = type;
    }

    public Diagramm name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @NotNull
    @Schema(name = "name", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Diagramm proven(Boolean proven) {
        this.proven = proven;
        return this;
    }

    /**
     * Get proven
     * @return proven
     */
    @NotNull
    @Schema(name = "proven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getProven() {
        return proven;
    }

    public void setProven(Boolean proven) {
        this.proven = proven;
    }

    public Diagramm comment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     * @return comment
     */
    @NotNull
    @Schema(name = "comment", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Diagramm compostionTechnique(CompostionTechniqueEnum compostionTechnique) {
        this.compostionTechnique = compostionTechnique;
        return this;
    }

    /**
     * Get compostionTechnique
     * @return compostionTechnique
     */
    @NotNull
    @Schema(name = "compostionTechnique", requiredMode = Schema.RequiredMode.REQUIRED)
    public CompostionTechniqueEnum getCompostionTechnique() {
        return compostionTechnique;
    }

    public void setCompostionTechnique(CompostionTechniqueEnum compostionTechnique) {
        this.compostionTechnique = compostionTechnique;
    }

    public Diagramm className(String className) {
        this.className = className;
        return this;
    }

    /**
     * Get className
     * @return className
     */
    @NotNull
    @Schema(name = "className", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Diagramm methodeName(String methodeName) {
        this.methodeName = methodeName;
        return this;
    }

    /**
     * Get methodeName
     * @return methodeName
     */
    @NotNull
    @Schema(name = "methodeName", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getMethodeName() {
        return methodeName;
    }

    public void setMethodeName(String methodeName) {
        this.methodeName = methodeName;
    }

    public Diagramm javaVariables(List<String> javaVariables) {
        this.javaVariables = javaVariables;
        return this;
    }

    public Diagramm addJavaVariablesItem(String javaVariablesItem) {
        this.javaVariables.add(javaVariablesItem);
        return this;
    }

    /**
     * Get javaVariables
     * @return javaVariables
     */
    @NotNull
    @Schema(name = "javaVariables", requiredMode = Schema.RequiredMode.REQUIRED)
    public List<String> getJavaVariables() {
        return javaVariables;
    }

    public void setJavaVariables(List<String> javaVariables) {
        this.javaVariables = javaVariables;
    }

    public Diagramm globalConditions(List<@Valid Condition> globalConditions) {
        this.globalConditions = globalConditions;
        return this;
    }

    public Diagramm addGlobalConditionsItem(Condition globalConditionsItem) {
        this.globalConditions.add(globalConditionsItem);
        return this;
    }

    /**
     * Get globalConditions
     * @return globalConditions
     */
    @NotNull
    @Schema(name = "globalConditions", requiredMode = Schema.RequiredMode.REQUIRED)
    public List<@Valid Condition> getGlobalConditions() {
        return globalConditions;
    }

    public void setGlobalConditions(List<@Valid Condition> globalConditions) {
        this.globalConditions = globalConditions;
    }

    public Diagramm preCondition(String preCondition) {
        this.preCondition = preCondition;
        return this;
    }

    /**
     * Get preCondition
     * @return preCondition
     */
    @NotNull
    @Schema(name = "preCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getPreCondition() {
        return preCondition;
    }

    public void setPreCondition(String preCondition) {
        this.preCondition = preCondition;
    }

    public Diagramm postCondition(String postCondition) {
        this.postCondition = postCondition;
        return this;
    }

    /**
     * Get postCondition
     * @return postCondition
     */
    @NotNull
    @Schema(name = "postCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getPostCondition() {
        return postCondition;
    }

    public void setPostCondition(String postCondition) {
        this.postCondition = postCondition;
    }

    public Diagramm statement(Statement statement) {
        this.statement = statement;
        return this;
    }

    /**
     * Get statement
     * @return statement
     */
    @Valid
    @NotNull
    @Schema(name = "statement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getStatement() {
        return statement;
    }

    public void setStatement(Statement statement) {
        this.statement = statement;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Diagramm diagramm = (Diagramm) o;
        return Objects.equals(this.urn, diagramm.urn) &&
            Objects.equals(this.inodeType, diagramm.inodeType) &&
            Objects.equals(this.type, diagramm.type) &&
            Objects.equals(this.name, diagramm.name) &&
            Objects.equals(this.proven, diagramm.proven) &&
            Objects.equals(this.comment, diagramm.comment) &&
            Objects.equals(this.compostionTechnique, diagramm.compostionTechnique) &&
            Objects.equals(this.className, diagramm.className) &&
            Objects.equals(this.methodeName, diagramm.methodeName) &&
            Objects.equals(this.javaVariables, diagramm.javaVariables) &&
            Objects.equals(this.globalConditions, diagramm.globalConditions) &&
            Objects.equals(this.preCondition, diagramm.preCondition) &&
            Objects.equals(this.postCondition, diagramm.postCondition) &&
            Objects.equals(this.statement, diagramm.statement);
    }

    @Override
    public int hashCode() {
        return Objects.hash(urn, inodeType, type, name, proven, comment, compostionTechnique, className, methodeName, javaVariables, globalConditions, preCondition, postCondition, statement);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Diagramm {\n");
        sb.append("    urn: ").append(toIndentedString(urn)).append("\n");
        sb.append("    inodeType: ").append(toIndentedString(inodeType)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    proven: ").append(toIndentedString(proven)).append("\n");
        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    compostionTechnique: ").append(toIndentedString(compostionTechnique)).append("\n");
        sb.append("    className: ").append(toIndentedString(className)).append("\n");
        sb.append("    methodeName: ").append(toIndentedString(methodeName)).append("\n");
        sb.append("    javaVariables: ").append(toIndentedString(javaVariables)).append("\n");
        sb.append("    globalConditions: ").append(toIndentedString(globalConditions)).append("\n");
        sb.append("    preCondition: ").append(toIndentedString(preCondition)).append("\n");
        sb.append("    postCondition: ").append(toIndentedString(postCondition)).append("\n");
        sb.append("    statement: ").append(toIndentedString(statement)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

