/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Inode
 */
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class Inode implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_URN = "urn";
    private String urn;

    public static final String JSON_PROPERTY_INODE_TYPE = "inodeType";
    private String inodeType;

    public Inode(String urn, String inodeType) {
        this.urn = urn;
        this.inodeType = inodeType;
    }

    public Inode urn(String urn) {
        this.urn = urn;
        return this;
    }

    /**
     * Get urn
     * @return urn
     */
    @NotNull
    @Schema(name = "urn", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getUrn() {
        return urn;
    }

    public void setUrn(String urn) {
        this.urn = urn;
    }

    public Inode inodeType(String inodeType) {
        this.inodeType = inodeType;
        return this;
    }

    /**
     * Get inodeType
     * @return inodeType
     */
    @NotNull
    @Schema(name = "inodeType", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getInodeType() {
        return inodeType;
    }

    public void setInodeType(String inodeType) {
        this.inodeType = inodeType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Inode inode = (Inode) o;
        return Objects.equals(this.urn, inode.urn) &&
            Objects.equals(this.inodeType, inode.inodeType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(urn, inodeType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Inode {\n");
        sb.append("    urn: ").append(toIndentedString(urn)).append("\n");
        sb.append("    inodeType: ").append(toIndentedString(inodeType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

