/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * File
 */
@Schema(name = "_file", description = "File")
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class ModelFile implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_URN = "urn";
    private String urn;

    public static final String JSON_PROPERTY_INODE_TYPE = "inodeType";
    private String inodeType;

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        KEY("key"),
        PROVE("prove"),
        JAVA("java"),
        DIAGRAM("diagram");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_TYPE = "type";
    private TypeEnum type;

    public ModelFile(String urn, String inodeType, TypeEnum type) {
        this.urn = urn;
        this.inodeType = inodeType;
        this.type = type;
    }

    public ModelFile urn(String urn) {
        this.urn = urn;
        return this;
    }

    /**
     * Get urn
     * @return urn
     */
    @NotNull
    @Schema(name = "urn", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getUrn() {
        return urn;
    }

    public void setUrn(String urn) {
        this.urn = urn;
    }

    public ModelFile inodeType(String inodeType) {
        this.inodeType = inodeType;
        return this;
    }

    /**
     * Get inodeType
     * @return inodeType
     */
    @NotNull
    @Schema(name = "inodeType", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getInodeType() {
        return inodeType;
    }

    public void setInodeType(String inodeType) {
        this.inodeType = inodeType;
    }

    public ModelFile type(TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     */
    @NotNull
    @Schema(name = "type", requiredMode = Schema.RequiredMode.REQUIRED)
    public TypeEnum getType() {
        return type;
    }

    public void setType(TypeEnum type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModelFile _file = (ModelFile) o;
        return Objects.equals(this.urn, _file.urn) &&
            Objects.equals(this.inodeType, _file.inodeType) &&
            Objects.equals(this.type, _file.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(urn, inodeType, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ModelFile {\n");
        sb.append("    urn: ").append(toIndentedString(urn)).append("\n");
        sb.append("    inodeType: ").append(toIndentedString(inodeType)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

