/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Position
 */
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class Position implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_XIN_PX = "xinPx";
    private Long xinPx;

    public static final String JSON_PROPERTY_YIN_PX = "yinPx";
    private Long yinPx;

    public Position() {
    }

    public Position xinPx(Long xinPx) {
        this.xinPx = xinPx;
        return this;
    }

    /**
     * Get xinPx
     * @return xinPx
     */
    @Schema(name = "xinPx", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    public Optional<Long> getXinPx() {
        return Optional.ofNullable(xinPx);
    }

    public void setXinPx(Long xinPx) {
        this.xinPx = xinPx;
    }

    public Position yinPx(Long yinPx) {
        this.yinPx = yinPx;
        return this;
    }

    /**
     * Get yinPx
     * @return yinPx
     */
    @Schema(name = "yinPx", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    public Optional<Long> getYinPx() {
        return Optional.ofNullable(yinPx);
    }

    public void setYinPx(Long yinPx) {
        this.yinPx = yinPx;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Position position = (Position) o;
        return Objects.equals(this.xinPx, position.xinPx) &&
            Objects.equals(this.yinPx, position.yinPx);
    }

    @Override
    public int hashCode() {
        return Objects.hash(xinPx, yinPx);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Position {\n");
        sb.append("    xinPx: ").append(toIndentedString(xinPx)).append("\n");
        sb.append("    yinPx: ").append(toIndentedString(yinPx)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

