/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import java.net.URI;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Problem
 */
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class Problem implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_TYPE = "type";
    private URI type = URI.create("about:blank");

    public static final String JSON_PROPERTY_TITLE = "title";
    private String title;

    public static final String JSON_PROPERTY_STATUS = "status";
    private Integer status;

    public static final String JSON_PROPERTY_DETAIL = "detail";
    private String detail;

    public static final String JSON_PROPERTY_INSTANCE = "instance";
    private URI instance;

    public Problem(URI type, String title, Integer status, String detail, URI instance) {
        this.type = type;
        this.title = title;
        this.status = status;
        this.detail = detail;
        this.instance = instance;
    }

    public Problem type(URI type) {
        this.type = type;
        return this;
    }

    /**
     * An absolute URI that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML). 
     * @return type
     */
    @NotNull
    @Schema(name = "type", example = "https://zalando.github.io/problem/constraint-violation", description = "An absolute URI that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML). ", requiredMode = Schema.RequiredMode.REQUIRED)
    public URI getType() {
        return type;
    }

    public void setType(URI type) {
        this.type = type;
    }

    public Problem title(String title) {
        this.title = title;
        return this;
    }

    /**
     * A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable 
     * @return title
     */
    @NotNull
    @Schema(name = "title", description = "A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable ", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Problem status(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem. 
     * minimum: 100
     * maximum: 600
     * @return status
     */
    @NotNull
    @Min(100)
    @Max(600)
    @Schema(name = "status", example = "503", description = "The HTTP status code generated by the origin server for this occurrence of the problem. ", requiredMode = Schema.RequiredMode.REQUIRED)
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Problem detail(String detail) {
        this.detail = detail;
        return this;
    }

    /**
     * A human readable explanation specific to this occurrence of the problem. 
     * @return detail
     */
    @NotNull
    @Schema(name = "detail", example = "Connection to database timed out", description = "A human readable explanation specific to this occurrence of the problem. ", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Problem instance(URI instance) {
        this.instance = instance;
        return this;
    }

    /**
     * An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. 
     * @return instance
     */
    @NotNull
    @Schema(name = "instance", description = "An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. ", requiredMode = Schema.RequiredMode.REQUIRED)
    public URI getInstance() {
        return instance;
    }

    public void setInstance(URI instance) {
        this.instance = instance;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Problem problem = (Problem) o;
        return Objects.equals(this.type, problem.type) &&
            Objects.equals(this.title, problem.title) &&
            Objects.equals(this.status, problem.status) &&
            Objects.equals(this.detail, problem.detail) &&
            Objects.equals(this.instance, problem.instance);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, title, status, detail, instance);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Problem {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
        sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

