/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import edu.kit.cbc.web.model.Condition;
import edu.kit.cbc.web.model.Position;
import edu.kit.cbc.web.model.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Repetition Statement
 */
@Schema(name = "repetition", description = "Repetition Statement")
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class Repetition implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_STATEMENT_TYPE = "statementType";
    private String statementType;

    public static final String JSON_PROPERTY_ID = "id";
    private Long id;

    public static final String JSON_PROPERTY_PROVEN = "proven";
    private Boolean proven;

    public static final String JSON_PROPERTY_COMMENT = "comment";
    private String comment;

    public static final String JSON_PROPERTY_PRE_CONDITION = "preCondition";
    private Condition preCondition;

    public static final String JSON_PROPERTY_POST_CONDITION = "postCondition";
    private Condition postCondition;

    public static final String JSON_PROPERTY_POSITION = "position";
    private Position position;

    public static final String JSON_PROPERTY_POST_PROVEN = "postProven";
    private Boolean postProven;

    public static final String JSON_PROPERTY_PRE_PROVEN = "preProven";
    private Boolean preProven;

    public static final String JSON_PROPERTY_VARIANT_PROVEN = "variantProven";
    private Boolean variantProven;

    public static final String JSON_PROPERTY_INVARIANT_CONDITION = "invariantCondition";
    private Condition invariantCondition;

    public static final String JSON_PROPERTY_GUARD_CONDITION = "guardCondition";
    private Condition guardCondition;

    public static final String JSON_PROPERTY_STATEMENTS = "statements";
    private List<Statement> statements = new ArrayList<>();

    public static final String JSON_PROPERTY_VARIANT = "variant";
    private String variant;

    public static final String JSON_PROPERTY_LOOP_STATEMENT = "loopStatement";
    private Statement loopStatement;

    public Repetition(String name, String statementType, Long id, Boolean proven, String comment, Condition preCondition, Condition postCondition, Position position, Boolean postProven, Boolean preProven, Boolean variantProven, Condition invariantCondition, Condition guardCondition, List<Statement> statements, String variant, Statement loopStatement) {
        this.name = name;
        this.statementType = statementType;
        this.id = id;
        this.proven = proven;
        this.comment = comment;
        this.preCondition = preCondition;
        this.postCondition = postCondition;
        this.position = position;
        this.postProven = postProven;
        this.preProven = preProven;
        this.variantProven = variantProven;
        this.invariantCondition = invariantCondition;
        this.guardCondition = guardCondition;
        this.statements = statements;
        this.variant = variant;
        this.loopStatement = loopStatement;
    }

    public Repetition name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @NotNull
    @Schema(name = "name", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Repetition statementType(String statementType) {
        this.statementType = statementType;
        return this;
    }

    /**
     * Get statementType
     * @return statementType
     */
    @NotNull
    @Schema(name = "statementType", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getStatementType() {
        return statementType;
    }

    public void setStatementType(String statementType) {
        this.statementType = statementType;
    }

    public Repetition id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Repetition proven(Boolean proven) {
        this.proven = proven;
        return this;
    }

    /**
     * Get proven
     * @return proven
     */
    @NotNull
    @Schema(name = "proven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getProven() {
        return proven;
    }

    public void setProven(Boolean proven) {
        this.proven = proven;
    }

    public Repetition comment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     * @return comment
     */
    @NotNull
    @Schema(name = "comment", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Repetition preCondition(Condition preCondition) {
        this.preCondition = preCondition;
        return this;
    }

    /**
     * Get preCondition
     * @return preCondition
     */
    @Valid
    @NotNull
    @Schema(name = "preCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPreCondition() {
        return preCondition;
    }

    public void setPreCondition(Condition preCondition) {
        this.preCondition = preCondition;
    }

    public Repetition postCondition(Condition postCondition) {
        this.postCondition = postCondition;
        return this;
    }

    /**
     * Get postCondition
     * @return postCondition
     */
    @Valid
    @NotNull
    @Schema(name = "postCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPostCondition() {
        return postCondition;
    }

    public void setPostCondition(Condition postCondition) {
        this.postCondition = postCondition;
    }

    public Repetition position(Position position) {
        this.position = position;
        return this;
    }

    /**
     * Get position
     * @return position
     */
    @Valid
    @NotNull
    @Schema(name = "position", requiredMode = Schema.RequiredMode.REQUIRED)
    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    public Repetition postProven(Boolean postProven) {
        this.postProven = postProven;
        return this;
    }

    /**
     * Get postProven
     * @return postProven
     */
    @NotNull
    @Schema(name = "postProven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getPostProven() {
        return postProven;
    }

    public void setPostProven(Boolean postProven) {
        this.postProven = postProven;
    }

    public Repetition preProven(Boolean preProven) {
        this.preProven = preProven;
        return this;
    }

    /**
     * Get preProven
     * @return preProven
     */
    @NotNull
    @Schema(name = "preProven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getPreProven() {
        return preProven;
    }

    public void setPreProven(Boolean preProven) {
        this.preProven = preProven;
    }

    public Repetition variantProven(Boolean variantProven) {
        this.variantProven = variantProven;
        return this;
    }

    /**
     * Get variantProven
     * @return variantProven
     */
    @NotNull
    @Schema(name = "variantProven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getVariantProven() {
        return variantProven;
    }

    public void setVariantProven(Boolean variantProven) {
        this.variantProven = variantProven;
    }

    public Repetition invariantCondition(Condition invariantCondition) {
        this.invariantCondition = invariantCondition;
        return this;
    }

    /**
     * Get invariantCondition
     * @return invariantCondition
     */
    @Valid
    @NotNull
    @Schema(name = "invariantCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getInvariantCondition() {
        return invariantCondition;
    }

    public void setInvariantCondition(Condition invariantCondition) {
        this.invariantCondition = invariantCondition;
    }

    public Repetition guardCondition(Condition guardCondition) {
        this.guardCondition = guardCondition;
        return this;
    }

    /**
     * Get guardCondition
     * @return guardCondition
     */
    @Valid
    @NotNull
    @Schema(name = "guardCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getGuardCondition() {
        return guardCondition;
    }

    public void setGuardCondition(Condition guardCondition) {
        this.guardCondition = guardCondition;
    }

    public Repetition statements(List<Statement> statements) {
        this.statements = statements;
        return this;
    }

    public Repetition addStatementsItem(Statement statementsItem) {
        this.statements.add(statementsItem);
        return this;
    }

    /**
     * Get statements
     * @return statements
     */
    @NotNull
    @Schema(name = "statements", requiredMode = Schema.RequiredMode.REQUIRED)
    public List<Statement> getStatements() {
        return statements;
    }

    public void setStatements(List<Statement> statements) {
        this.statements = statements;
    }

    public Repetition variant(String variant) {
        this.variant = variant;
        return this;
    }

    /**
     * Get variant
     * @return variant
     */
    @NotNull
    @Schema(name = "variant", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getVariant() {
        return variant;
    }

    public void setVariant(String variant) {
        this.variant = variant;
    }

    public Repetition loopStatement(Statement loopStatement) {
        this.loopStatement = loopStatement;
        return this;
    }

    /**
     * Get loopStatement
     * @return loopStatement
     */
    @Valid
    @NotNull
    @Schema(name = "loopStatement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getLoopStatement() {
        return loopStatement;
    }

    public void setLoopStatement(Statement loopStatement) {
        this.loopStatement = loopStatement;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Repetition repetition = (Repetition) o;
        return Objects.equals(this.name, repetition.name) &&
            Objects.equals(this.statementType, repetition.statementType) &&
            Objects.equals(this.id, repetition.id) &&
            Objects.equals(this.proven, repetition.proven) &&
            Objects.equals(this.comment, repetition.comment) &&
            Objects.equals(this.preCondition, repetition.preCondition) &&
            Objects.equals(this.postCondition, repetition.postCondition) &&
            Objects.equals(this.position, repetition.position) &&
            Objects.equals(this.postProven, repetition.postProven) &&
            Objects.equals(this.preProven, repetition.preProven) &&
            Objects.equals(this.variantProven, repetition.variantProven) &&
            Objects.equals(this.invariantCondition, repetition.invariantCondition) &&
            Objects.equals(this.guardCondition, repetition.guardCondition) &&
            Objects.equals(this.statements, repetition.statements) &&
            Objects.equals(this.variant, repetition.variant) &&
            Objects.equals(this.loopStatement, repetition.loopStatement);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, statementType, id, proven, comment, preCondition, postCondition, position, postProven, preProven, variantProven, invariantCondition, guardCondition, statements, variant, loopStatement);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Repetition {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    statementType: ").append(toIndentedString(statementType)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    proven: ").append(toIndentedString(proven)).append("\n");
        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    preCondition: ").append(toIndentedString(preCondition)).append("\n");
        sb.append("    postCondition: ").append(toIndentedString(postCondition)).append("\n");
        sb.append("    position: ").append(toIndentedString(position)).append("\n");
        sb.append("    postProven: ").append(toIndentedString(postProven)).append("\n");
        sb.append("    preProven: ").append(toIndentedString(preProven)).append("\n");
        sb.append("    variantProven: ").append(toIndentedString(variantProven)).append("\n");
        sb.append("    invariantCondition: ").append(toIndentedString(invariantCondition)).append("\n");
        sb.append("    guardCondition: ").append(toIndentedString(guardCondition)).append("\n");
        sb.append("    statements: ").append(toIndentedString(statements)).append("\n");
        sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
        sb.append("    loopStatement: ").append(toIndentedString(loopStatement)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

