/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import edu.kit.cbc.web.model.Condition;
import edu.kit.cbc.web.model.Position;
import edu.kit.cbc.web.model.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Selection Statement
 */
@Schema(name = "selection", description = "Selection Statement")
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Introspected
public class Selection implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_STATEMENT_TYPE = "statementType";
    private String statementType;

    public static final String JSON_PROPERTY_ID = "id";
    private Long id;

    public static final String JSON_PROPERTY_PROVEN = "proven";
    private Boolean proven;

    public static final String JSON_PROPERTY_COMMENT = "comment";
    private String comment;

    public static final String JSON_PROPERTY_PRE_CONDITION = "preCondition";
    private Condition preCondition;

    public static final String JSON_PROPERTY_POST_CONDITION = "postCondition";
    private Condition postCondition;

    public static final String JSON_PROPERTY_POSITION = "position";
    private Position position;

    public static final String JSON_PROPERTY_PRE_PROVEN = "preProven";
    private Boolean preProven;

    public static final String JSON_PROPERTY_GUARDS = "guards";
    private List<@Valid Condition> guards = null;

    public static final String JSON_PROPERTY_STATEMENTS = "statements";
    private List<Statement> statements = null;

    public Selection(String name, String statementType, Long id, Boolean proven, String comment, Condition preCondition, Condition postCondition, Position position, Boolean preProven) {
        this.name = name;
        this.statementType = statementType;
        this.id = id;
        this.proven = proven;
        this.comment = comment;
        this.preCondition = preCondition;
        this.postCondition = postCondition;
        this.position = position;
        this.preProven = preProven;
    }

    public Selection name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @NotNull
    @Schema(name = "name", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Selection statementType(String statementType) {
        this.statementType = statementType;
        return this;
    }

    /**
     * Get statementType
     * @return statementType
     */
    @NotNull
    @Schema(name = "statementType", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getStatementType() {
        return statementType;
    }

    public void setStatementType(String statementType) {
        this.statementType = statementType;
    }

    public Selection id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Selection proven(Boolean proven) {
        this.proven = proven;
        return this;
    }

    /**
     * Get proven
     * @return proven
     */
    @NotNull
    @Schema(name = "proven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getProven() {
        return proven;
    }

    public void setProven(Boolean proven) {
        this.proven = proven;
    }

    public Selection comment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     * @return comment
     */
    @NotNull
    @Schema(name = "comment", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Selection preCondition(Condition preCondition) {
        this.preCondition = preCondition;
        return this;
    }

    /**
     * Get preCondition
     * @return preCondition
     */
    @Valid
    @NotNull
    @Schema(name = "preCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPreCondition() {
        return preCondition;
    }

    public void setPreCondition(Condition preCondition) {
        this.preCondition = preCondition;
    }

    public Selection postCondition(Condition postCondition) {
        this.postCondition = postCondition;
        return this;
    }

    /**
     * Get postCondition
     * @return postCondition
     */
    @Valid
    @NotNull
    @Schema(name = "postCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPostCondition() {
        return postCondition;
    }

    public void setPostCondition(Condition postCondition) {
        this.postCondition = postCondition;
    }

    public Selection position(Position position) {
        this.position = position;
        return this;
    }

    /**
     * Get position
     * @return position
     */
    @Valid
    @NotNull
    @Schema(name = "position", requiredMode = Schema.RequiredMode.REQUIRED)
    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    public Selection preProven(Boolean preProven) {
        this.preProven = preProven;
        return this;
    }

    /**
     * Get preProven
     * @return preProven
     */
    @NotNull
    @Schema(name = "preProven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getPreProven() {
        return preProven;
    }

    public void setPreProven(Boolean preProven) {
        this.preProven = preProven;
    }

    public Selection guards(List<@Valid Condition> guards) {
        this.guards = guards;
        return this;
    }

    public Selection addGuardsItem(Condition guardsItem) {
        if (this.guards == null) {
            this.guards = new ArrayList<>();
        }
        this.guards.add(guardsItem);
        return this;
    }

    /**
     * Get guards
     * @return guards
     */
    @Schema(name = "guards", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    public Optional<List<@Valid Condition>> getGuards() {
        return Optional.ofNullable(guards);
    }

    public void setGuards(List<@Valid Condition> guards) {
        this.guards = guards;
    }

    public Selection statements(List<Statement> statements) {
        this.statements = statements;
        return this;
    }

    public Selection addStatementsItem(Statement statementsItem) {
        if (this.statements == null) {
            this.statements = new ArrayList<>();
        }
        this.statements.add(statementsItem);
        return this;
    }

    /**
     * Get statements
     * @return statements
     */
    @Schema(name = "statements", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    public Optional<List<Statement>> getStatements() {
        return Optional.ofNullable(statements);
    }

    public void setStatements(List<Statement> statements) {
        this.statements = statements;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Selection selection = (Selection) o;
        return Objects.equals(this.name, selection.name) &&
            Objects.equals(this.statementType, selection.statementType) &&
            Objects.equals(this.id, selection.id) &&
            Objects.equals(this.proven, selection.proven) &&
            Objects.equals(this.comment, selection.comment) &&
            Objects.equals(this.preCondition, selection.preCondition) &&
            Objects.equals(this.postCondition, selection.postCondition) &&
            Objects.equals(this.position, selection.position) &&
            Objects.equals(this.preProven, selection.preProven) &&
            Objects.equals(this.guards, selection.guards) &&
            Objects.equals(this.statements, selection.statements);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, statementType, id, proven, comment, preCondition, postCondition, position, preProven, guards, statements);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Selection {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    statementType: ").append(toIndentedString(statementType)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    proven: ").append(toIndentedString(proven)).append("\n");
        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    preCondition: ").append(toIndentedString(preCondition)).append("\n");
        sb.append("    postCondition: ").append(toIndentedString(postCondition)).append("\n");
        sb.append("    position: ").append(toIndentedString(position)).append("\n");
        sb.append("    preProven: ").append(toIndentedString(preProven)).append("\n");
        sb.append("    guards: ").append(toIndentedString(guards)).append("\n");
        sb.append("    statements: ").append(toIndentedString(statements)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

