/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Optional;
import edu.kit.cbc.web.model.Composition;
import edu.kit.cbc.web.model.Condition;
import edu.kit.cbc.web.model.Position;
import edu.kit.cbc.web.model.Repetition;
import edu.kit.cbc.web.model.Selection;
import edu.kit.cbc.web.model.Simple;
import edu.kit.cbc.web.model.StrongWeak;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.*;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Statement
 */
@io.micronaut.serde.annotation.Serdeable
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@JsonIgnoreProperties(
  value = "statementType", // ignore manually set statementType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the statementType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "statementType")
@JsonSubTypes({
  @JsonSubTypes.Type(value = Composition.class, name = "compositon"),
  @JsonSubTypes.Type(value = Repetition.class, name = "repetition"),
  @JsonSubTypes.Type(value = Selection.class, name = "selection"),
  @JsonSubTypes.Type(value = Simple.class, name = "simple"),
  @JsonSubTypes.Type(value = StrongWeak.class, name = "strongWeak"),
  @JsonSubTypes.Type(value = Composition.class, name = "composition"),
})

@Introspected
public class Statement implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_STATEMENT_TYPE = "statementType";
    protected String statementType;

    public static final String JSON_PROPERTY_ID = "id";
    private Long id;

    public static final String JSON_PROPERTY_PROVEN = "proven";
    private Boolean proven;

    public static final String JSON_PROPERTY_COMMENT = "comment";
    private String comment;

    public static final String JSON_PROPERTY_PRE_CONDITION = "preCondition";
    private Condition preCondition;

    public static final String JSON_PROPERTY_POST_CONDITION = "postCondition";
    private Condition postCondition;

    public static final String JSON_PROPERTY_POSITION = "position";
    private Position position;

    public static final String JSON_PROPERTY_INTERMEDIATE_CONDITION = "intermediateCondition";
    private Condition intermediateCondition;

    public static final String JSON_PROPERTY_LEFT_STATEMENT = "leftStatement";
    private Statement leftStatement;

    public static final String JSON_PROPERTY_RIGHT_STATEMENT = "rightStatement";
    private Statement rightStatement;

    public static final String JSON_PROPERTY_POST_PROVEN = "postProven";
    private Boolean postProven;

    public static final String JSON_PROPERTY_PRE_PROVEN = "preProven";
    private Boolean preProven;

    public static final String JSON_PROPERTY_VARIANT_PROVEN = "variantProven";
    private Boolean variantProven;

    public static final String JSON_PROPERTY_INVARIANT_CONDITION = "invariantCondition";
    private Condition invariantCondition;

    public static final String JSON_PROPERTY_GUARD_CONDITION = "guardCondition";
    private Condition guardCondition;

    public static final String JSON_PROPERTY_STATEMENTS = "statements";
    private List<Statement> statements = new ArrayList<>();

    public static final String JSON_PROPERTY_VARIANT = "variant";
    private String variant;

    public static final String JSON_PROPERTY_LOOP_STATEMENT = "loopStatement";
    private Statement loopStatement;

    public static final String JSON_PROPERTY_GUARDS = "guards";
    private List<@Valid Condition> guards = null;

    public static final String JSON_PROPERTY_STATEMENT = "statement";
    private Statement statement;

    public Statement(String name, String statementType, Long id, Boolean proven, String comment, Condition preCondition, Condition postCondition, Position position, Condition intermediateCondition, Statement leftStatement, Statement rightStatement, Boolean postProven, Boolean preProven, Boolean variantProven, Condition invariantCondition, Condition guardCondition, List<Statement> statements, String variant, Statement loopStatement, Statement statement) {
        this.name = name;
        this.statementType = statementType;
        this.id = id;
        this.proven = proven;
        this.comment = comment;
        this.preCondition = preCondition;
        this.postCondition = postCondition;
        this.position = position;
        this.intermediateCondition = intermediateCondition;
        this.leftStatement = leftStatement;
        this.rightStatement = rightStatement;
        this.postProven = postProven;
        this.preProven = preProven;
        this.variantProven = variantProven;
        this.invariantCondition = invariantCondition;
        this.guardCondition = guardCondition;
        this.statements = statements;
        this.variant = variant;
        this.loopStatement = loopStatement;
        this.statement = statement;
    }

    public Statement name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @NotNull
    @Schema(name = "name", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Statement statementType(String statementType) {
        this.statementType = statementType;
        return this;
    }

    /**
     * Get statementType
     * @return statementType
     */
    @NotNull
    @Schema(name = "statementType", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getStatementType() {
        return statementType;
    }

    public void setStatementType(String statementType) {
        this.statementType = statementType;
    }

    public Statement id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Statement proven(Boolean proven) {
        this.proven = proven;
        return this;
    }

    /**
     * Get proven
     * @return proven
     */
    @NotNull
    @Schema(name = "proven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getProven() {
        return proven;
    }

    public void setProven(Boolean proven) {
        this.proven = proven;
    }

    public Statement comment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     * @return comment
     */
    @NotNull
    @Schema(name = "comment", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Statement preCondition(Condition preCondition) {
        this.preCondition = preCondition;
        return this;
    }

    /**
     * Get preCondition
     * @return preCondition
     */
    @Valid
    @NotNull
    @Schema(name = "preCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPreCondition() {
        return preCondition;
    }

    public void setPreCondition(Condition preCondition) {
        this.preCondition = preCondition;
    }

    public Statement postCondition(Condition postCondition) {
        this.postCondition = postCondition;
        return this;
    }

    /**
     * Get postCondition
     * @return postCondition
     */
    @Valid
    @NotNull
    @Schema(name = "postCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getPostCondition() {
        return postCondition;
    }

    public void setPostCondition(Condition postCondition) {
        this.postCondition = postCondition;
    }

    public Statement position(Position position) {
        this.position = position;
        return this;
    }

    /**
     * Get position
     * @return position
     */
    @Valid
    @NotNull
    @Schema(name = "position", requiredMode = Schema.RequiredMode.REQUIRED)
    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    public Statement intermediateCondition(Condition intermediateCondition) {
        this.intermediateCondition = intermediateCondition;
        return this;
    }

    /**
     * Get intermediateCondition
     * @return intermediateCondition
     */
    @Valid
    @NotNull
    @Schema(name = "intermediateCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getIntermediateCondition() {
        return intermediateCondition;
    }

    public void setIntermediateCondition(Condition intermediateCondition) {
        this.intermediateCondition = intermediateCondition;
    }

    public Statement leftStatement(Statement leftStatement) {
        this.leftStatement = leftStatement;
        return this;
    }

    /**
     * Get leftStatement
     * @return leftStatement
     */
    @Valid
    @NotNull
    @Schema(name = "leftStatement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getLeftStatement() {
        return leftStatement;
    }

    public void setLeftStatement(Statement leftStatement) {
        this.leftStatement = leftStatement;
    }

    public Statement rightStatement(Statement rightStatement) {
        this.rightStatement = rightStatement;
        return this;
    }

    /**
     * Get rightStatement
     * @return rightStatement
     */
    @Valid
    @NotNull
    @Schema(name = "rightStatement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getRightStatement() {
        return rightStatement;
    }

    public void setRightStatement(Statement rightStatement) {
        this.rightStatement = rightStatement;
    }

    public Statement postProven(Boolean postProven) {
        this.postProven = postProven;
        return this;
    }

    /**
     * Get postProven
     * @return postProven
     */
    @NotNull
    @Schema(name = "postProven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getPostProven() {
        return postProven;
    }

    public void setPostProven(Boolean postProven) {
        this.postProven = postProven;
    }

    public Statement preProven(Boolean preProven) {
        this.preProven = preProven;
        return this;
    }

    /**
     * Get preProven
     * @return preProven
     */
    @NotNull
    @Schema(name = "preProven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getPreProven() {
        return preProven;
    }

    public void setPreProven(Boolean preProven) {
        this.preProven = preProven;
    }

    public Statement variantProven(Boolean variantProven) {
        this.variantProven = variantProven;
        return this;
    }

    /**
     * Get variantProven
     * @return variantProven
     */
    @NotNull
    @Schema(name = "variantProven", requiredMode = Schema.RequiredMode.REQUIRED)
    public Boolean getVariantProven() {
        return variantProven;
    }

    public void setVariantProven(Boolean variantProven) {
        this.variantProven = variantProven;
    }

    public Statement invariantCondition(Condition invariantCondition) {
        this.invariantCondition = invariantCondition;
        return this;
    }

    /**
     * Get invariantCondition
     * @return invariantCondition
     */
    @Valid
    @NotNull
    @Schema(name = "invariantCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getInvariantCondition() {
        return invariantCondition;
    }

    public void setInvariantCondition(Condition invariantCondition) {
        this.invariantCondition = invariantCondition;
    }

    public Statement guardCondition(Condition guardCondition) {
        this.guardCondition = guardCondition;
        return this;
    }

    /**
     * Get guardCondition
     * @return guardCondition
     */
    @Valid
    @NotNull
    @Schema(name = "guardCondition", requiredMode = Schema.RequiredMode.REQUIRED)
    public Condition getGuardCondition() {
        return guardCondition;
    }

    public void setGuardCondition(Condition guardCondition) {
        this.guardCondition = guardCondition;
    }

    public Statement statements(List<Statement> statements) {
        this.statements = statements;
        return this;
    }

    public Statement addStatementsItem(Statement statementsItem) {
        this.statements.add(statementsItem);
        return this;
    }

    /**
     * Get statements
     * @return statements
     */
    @NotNull
    @Schema(name = "statements", requiredMode = Schema.RequiredMode.REQUIRED)
    public List<Statement> getStatements() {
        return statements;
    }

    public void setStatements(List<Statement> statements) {
        this.statements = statements;
    }

    public Statement variant(String variant) {
        this.variant = variant;
        return this;
    }

    /**
     * Get variant
     * @return variant
     */
    @NotNull
    @Schema(name = "variant", requiredMode = Schema.RequiredMode.REQUIRED)
    public String getVariant() {
        return variant;
    }

    public void setVariant(String variant) {
        this.variant = variant;
    }

    public Statement loopStatement(Statement loopStatement) {
        this.loopStatement = loopStatement;
        return this;
    }

    /**
     * Get loopStatement
     * @return loopStatement
     */
    @Valid
    @NotNull
    @Schema(name = "loopStatement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getLoopStatement() {
        return loopStatement;
    }

    public void setLoopStatement(Statement loopStatement) {
        this.loopStatement = loopStatement;
    }

    public Statement guards(List<@Valid Condition> guards) {
        this.guards = guards;
        return this;
    }

    public Statement addGuardsItem(Condition guardsItem) {
        if (this.guards == null) {
            this.guards = new ArrayList<>();
        }
        this.guards.add(guardsItem);
        return this;
    }

    /**
     * Get guards
     * @return guards
     */
    @Schema(name = "guards", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    public Optional<List<@Valid Condition>> getGuards() {
        return Optional.ofNullable(guards);
    }

    public void setGuards(List<@Valid Condition> guards) {
        this.guards = guards;
    }

    public Statement statement(Statement statement) {
        this.statement = statement;
        return this;
    }

    /**
     * Get statement
     * @return statement
     */
    @Valid
    @NotNull
    @Schema(name = "statement", requiredMode = Schema.RequiredMode.REQUIRED)
    public Statement getStatement() {
        return statement;
    }

    public void setStatement(Statement statement) {
        this.statement = statement;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Statement statement = (Statement) o;
        return Objects.equals(this.name, statement.name) &&
            Objects.equals(this.statementType, statement.statementType) &&
            Objects.equals(this.id, statement.id) &&
            Objects.equals(this.proven, statement.proven) &&
            Objects.equals(this.comment, statement.comment) &&
            Objects.equals(this.preCondition, statement.preCondition) &&
            Objects.equals(this.postCondition, statement.postCondition) &&
            Objects.equals(this.position, statement.position) &&
            Objects.equals(this.intermediateCondition, statement.intermediateCondition) &&
            Objects.equals(this.leftStatement, statement.leftStatement) &&
            Objects.equals(this.rightStatement, statement.rightStatement) &&
            Objects.equals(this.postProven, statement.postProven) &&
            Objects.equals(this.preProven, statement.preProven) &&
            Objects.equals(this.variantProven, statement.variantProven) &&
            Objects.equals(this.invariantCondition, statement.invariantCondition) &&
            Objects.equals(this.guardCondition, statement.guardCondition) &&
            Objects.equals(this.statements, statement.statements) &&
            Objects.equals(this.variant, statement.variant) &&
            Objects.equals(this.loopStatement, statement.loopStatement) &&
            Objects.equals(this.guards, statement.guards) &&
            Objects.equals(this.statement, statement.statement);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, statementType, id, proven, comment, preCondition, postCondition, position, intermediateCondition, leftStatement, rightStatement, postProven, preProven, variantProven, invariantCondition, guardCondition, statements, variant, loopStatement, guards, statement);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Statement {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    statementType: ").append(toIndentedString(statementType)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    proven: ").append(toIndentedString(proven)).append("\n");
        sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
        sb.append("    preCondition: ").append(toIndentedString(preCondition)).append("\n");
        sb.append("    postCondition: ").append(toIndentedString(postCondition)).append("\n");
        sb.append("    position: ").append(toIndentedString(position)).append("\n");
        sb.append("    intermediateCondition: ").append(toIndentedString(intermediateCondition)).append("\n");
        sb.append("    leftStatement: ").append(toIndentedString(leftStatement)).append("\n");
        sb.append("    rightStatement: ").append(toIndentedString(rightStatement)).append("\n");
        sb.append("    postProven: ").append(toIndentedString(postProven)).append("\n");
        sb.append("    preProven: ").append(toIndentedString(preProven)).append("\n");
        sb.append("    variantProven: ").append(toIndentedString(variantProven)).append("\n");
        sb.append("    invariantCondition: ").append(toIndentedString(invariantCondition)).append("\n");
        sb.append("    guardCondition: ").append(toIndentedString(guardCondition)).append("\n");
        sb.append("    statements: ").append(toIndentedString(statements)).append("\n");
        sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
        sb.append("    loopStatement: ").append(toIndentedString(loopStatement)).append("\n");
        sb.append("    guards: ").append(toIndentedString(guards)).append("\n");
        sb.append("    statement: ").append(toIndentedString(statement)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

