openapi: '3.0.2'
info:
  title: Webcorc
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /projects:
    $ref: './paths/projects.yml'
  
  /projects/{id}:
    $ref: './paths/project.yml'

  /projects/{id}/files:
    $ref: './paths/projectFiles.yml'

  /projects/{id}/files/{urn}:
    $ref: './paths/projectFile.yml'

  /editor/graph/export:
    $ref: './paths/editor/exportGraph.yml'

  /editor/workspace/export:
    $ref: './paths/editor/exportWorkspace.yml'
  
  /editor/generate: 
    $ref: './paths/editor/generate.yml'

  /editor/verify:
     $ref: './paths/editor/verify.yml'
        
  /editor/jobs/{id}:
    $ref: './paths/editor/jobs.yml'