/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.controller;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.micronaut.security.annotation.Secured;
import io.micronaut.security.rules.SecurityRule;
import reactor.core.publisher.Mono;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.exceptions.HttpStatusException;
import edu.kit.cbc.web.model.Formula;
import edu.kit.cbc.web.model.Problem;
import java.util.UUID;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;

@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Controller
@Tag(name = "Editor", description = "The Editor API")
public class EditorController {
    /**
     * Export current Workspace
     *
     */
    @Operation(
        operationId = "exportWorkspace",
        summary = "Export current Workspace",
        responses = {
            @ApiResponse(responseCode = "200", description = "Include Zip file")
        }
    )
    @Post(uri="/editor/export")
    @Produces(value = {})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Void> exportWorkspace() {
        // TODO implement exportWorkspace();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * generateJavaCode
     *
     */
    @Operation(
        operationId = "generateJavaCode",
        responses = {
            @ApiResponse(responseCode = "200", description = "Include Zip file of Java Code")
        }
    )
    @Post(uri="/editor/generate")
    @Produces(value = {})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Void> generateJavaCode() {
        // TODO implement generateJavaCode();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Get Job Status Over Websocket
     * Get Job Status
     *
     * @param id  (required)
     */
    @Operation(
        operationId = "readJobStatusByUUID",
        summary = "Get Job Status Over Websocket",
        responses = {
            @ApiResponse(responseCode = "200", description = "Webhook opened"),
            @ApiResponse(responseCode = "404", description = "Job by id not found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", required = true)
        }
    )
    @Get(uri="/editor/jobs/{id}")
    @Produces(value = {"application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Void> readJobStatusByUUID(
        @PathVariable(value="id") @NotNull UUID id
    ) {
        // TODO implement readJobStatusByUUID();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Verify Formula
     * Verify Formula
     *
     * @param formula Formula to verify (optional)
     */
    @Operation(
        operationId = "verifyFormula",
        summary = "Verify Formula",
        responses = {
            @ApiResponse(responseCode = "202", description = "Verification Job accepted"),
            @ApiResponse(responseCode = "400", description = "Malformed Request Body", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "formula", description = "Formula to verify")
        }
    )
    @Post(uri="/editor/verify")
    @Produces(value = {"application/problem+json"})
    @Consumes(value = {"application/json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Void> verifyFormula(
        @Body @Nullable @Valid Formula formula
    ) {
        // TODO implement verifyFormula();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }

}
