/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.controller;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.micronaut.security.annotation.Secured;
import io.micronaut.security.rules.SecurityRule;
import reactor.core.publisher.Mono;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.exceptions.HttpStatusException;
import edu.kit.cbc.web.model.Create;
import edu.kit.cbc.web.model.Problem;
import edu.kit.cbc.web.model.Read;
import java.util.UUID;
import edu.kit.cbc.web.model.Update;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;

@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Controller
@Tag(name = "ProjectManagement", description = "The ProjectManagement API")
public class ProjectManagementController {
    /**
     * Create new Project
     * Create a new Project
     *
     * @param create Give Project a name (required)
     * @return Read
     */
    @Operation(
        operationId = "createProject",
        summary = "Create new Project",
        responses = {
            @ApiResponse(responseCode = "201", description = "Sucessfull creation of Project", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Read.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Read.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Payload", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "create", description = "Give Project a name", required = true)
        }
    )
    @Post(uri="/projects")
    @Produces(value = {"application/json", "application/problem+json"})
    @Consumes(value = {"application/json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Read> createProject(
        @Body @NotNull @Valid Create create
    ) {
        // TODO implement createProject();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Delete Project
     * Delete Project By Id
     *
     * @param id id of project (required)
     */
    @Operation(
        operationId = "deleteProjectById",
        summary = "Delete Project",
        responses = {
            @ApiResponse(responseCode = "204", description = "Successfull deletion of project"),
            @ApiResponse(responseCode = "404", description = "Project by id not found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", description = "id of project", required = true)
        }
    )
    @Delete(uri="/projects/{id}")
    @Produces(value = {"application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Void> deleteProjectById(
        @PathVariable(value="id") @NotNull UUID id
    ) {
        // TODO implement deleteProjectById();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Get Project by id
     * Get Information about Project by id.
     *
     * @param id id of project (required)
     * @return Read
     */
    @Operation(
        operationId = "readProjectById",
        summary = "Get Project by id",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successfull read of project by id", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Read.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Read.class))
            }),
            @ApiResponse(responseCode = "404", description = "Project by id not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", description = "id of project", required = true)
        }
    )
    @Get(uri="/projects/{id}")
    @Produces(value = {"application/json", "application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Read> readProjectById(
        @PathVariable(value="id") @NotNull UUID id
    ) {
        // TODO implement readProjectById();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Update Project
     * Update Project by its id
     *
     * @param id id of project (required)
     * @param update Representation of updated Project (required)
     * @return Read
     */
    @Operation(
        operationId = "updateProjectById",
        summary = "Update Project",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successfull update of project by id", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Read.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Read.class))
            }),
            @ApiResponse(responseCode = "404", description = "Project by id not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", description = "id of project", required = true),
            @Parameter(name = "update", description = "Representation of updated Project", required = true)
        }
    )
    @Put(uri="/projects/{id}")
    @Produces(value = {"application/json", "application/problem+json"})
    @Consumes(value = {"application/json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Read> updateProjectById(
        @PathVariable(value="id") @NotNull UUID id, 
        @Body @NotNull @Valid Update update
    ) {
        // TODO implement updateProjectById();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }

}
