/*
 * Webcorc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package edu.kit.cbc.web.controller;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.micronaut.security.annotation.Secured;
import io.micronaut.security.rules.SecurityRule;
import reactor.core.publisher.Mono;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.exceptions.HttpStatusException;
import edu.kit.cbc.web.model.Directory;
import edu.kit.cbc.web.model.Filecontent;
import edu.kit.cbc.web.model.Problem;
import java.util.UUID;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;

@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", comments = "Generator version: 7.8.0-SNAPSHOT")
@Controller
@Tag(name = "ProjectFileManagement", description = "The ProjectFileManagement API")
public class ProjectFileManagementController {
    /**
     * Create File / Directory
     * Create new File / Directory
     *
     * @param id  (required)
     * @param urn  (required)
     * @return Filecontent
     */
    @Operation(
        operationId = "createFileorDirectory",
        summary = "Create File / Directory",
        responses = {
            @ApiResponse(responseCode = "201", description = "Successfull creation of file", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Filecontent.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Filecontent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Malformed requestBody", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "404", description = "Project by Id or file urn not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", required = true),
            @Parameter(name = "urn", required = true)
        }
    )
    @Post(uri="/projects/{id}/files/{urn}")
    @Produces(value = {"application/json", "application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Filecontent> createFileorDirectory(
        @PathVariable(value="id") @NotNull UUID id, 
        @PathVariable(value="urn") @NotNull String urn
    ) {
        // TODO implement createFileorDirectory();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Delete File
     * Delete File
     *
     * @param id  (required)
     * @param urn  (required)
     */
    @Operation(
        operationId = "deleteFileByURN",
        summary = "Delete File",
        responses = {
            @ApiResponse(responseCode = "204", description = "Successfull deletion of file"),
            @ApiResponse(responseCode = "404", description = "Project by id or file by urn not found.", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", required = true),
            @Parameter(name = "urn", required = true)
        }
    )
    @Delete(uri="/projects/{id}/files/{urn}")
    @Produces(value = {"application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Void> deleteFileByURN(
        @PathVariable(value="id") @NotNull UUID id, 
        @PathVariable(value="urn") @NotNull String urn
    ) {
        // TODO implement deleteFileByURN();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Get File / Directory Structure (optional??)
     * Create new File / Directory
     *
     * @param id  (required)
     * @return Directory
     */
    @Operation(
        operationId = "getFileTreeByProjectId",
        summary = "Get File / Directory Structure (optional??)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successfull read of file tree", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Directory.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Directory.class))
            }),
            @ApiResponse(responseCode = "404", description = "Project by Id or file urn not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", required = true)
        }
    )
    @Get(uri="/projects/{id}/files")
    @Produces(value = {"application/json", "application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Directory> getFileTreeByProjectId(
        @PathVariable(value="id") @NotNull UUID id
    ) {
        // TODO implement getFileTreeByProjectId();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Get Directory or file contents
     * Read all Project Files
     *
     * @param id  (required)
     * @param urn  (required)
     * @return Filecontent
     */
    @Operation(
        operationId = "readFileContentByURN",
        summary = "Get Directory or file contents",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successfull Read of Project File / Directory content", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Filecontent.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Filecontent.class))
            }),
            @ApiResponse(responseCode = "404", description = "Project by Id or file urn not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", required = true),
            @Parameter(name = "urn", required = true)
        }
    )
    @Get(uri="/projects/{id}/files/{urn}")
    @Produces(value = {"application/json", "application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Filecontent> readFileContentByURN(
        @PathVariable(value="id") @NotNull UUID id, 
        @PathVariable(value="urn") @NotNull String urn
    ) {
        // TODO implement readFileContentByURN();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }


    /**
     * Update File Content
     * Update file content
     *
     * @param id  (required)
     * @param urn  (required)
     * @return Filecontent
     */
    @Operation(
        operationId = "updateProjectFileByURN",
        summary = "Update File Content",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successfull update of file content", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Filecontent.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Filecontent.class))
            }),
            @ApiResponse(responseCode = "404", description = "Project by id or file by urn not found.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "500", description = "Generic Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        },
        parameters = {
            @Parameter(name = "id", required = true),
            @Parameter(name = "urn", required = true)
        }
    )
    @Put(uri="/projects/{id}/files/{urn}")
    @Produces(value = {"application/json", "application/problem+json"})
    @Secured({SecurityRule.IS_ANONYMOUS})
    public Mono<Filecontent> updateProjectFileByURN(
        @PathVariable(value="id") @NotNull UUID id, 
        @PathVariable(value="urn") @NotNull String urn
    ) {
        // TODO implement updateProjectFileByURN();
        return Mono.error(new HttpStatusException(HttpStatus.NOT_IMPLEMENTED, null));
    }

}
