{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  {{- with .Values.ingress.entryPoints }}
  entryPoints:
    {{-  toYaml . | nindent 4}}
  {{- end}}
  routes:
  - match: Host(`{{ .Values.ingress.domain }}`)
    kind: Rule
    services:
    - name: {{ .Values.serviceName }}
      port: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    certResolver: {{ .Values.ingress.tls.resolver }}
  {{- end}}
{{- end}}
